##########################################################################################
# 
# Copyright International Business Machines Corp. 2014, 2020.
# 
# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership. Licensed under the Apache License,
# Version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
##########################################################################################
# Author: Dennis Riddlemoser
# This script generates reports based on tar files produced by ConfigDumpLiberty.sh
##########################################################################################
# Change history:
# Date        Ref  Who  Comments
# 2019/05/25  0030 DWR  Makeing date/time stapms a conditional match
# 2019/08/19  0036 DWR  Exit with syntax if less than two parameters on the command line
# 
# 
import ConfigUtils as cu
import sys
import time
import re
import os
import traceback
import glob
#Load libraries from where the path they are installed.
path = os.getenv('IBM_JAVA_COMMAND_LINE')
if path == None or len(path) == 0:
	path=sys.argv[0]
else:
	path=path[path.find("-f") + 2:].strip()
path=path.split(' ')[0]
if path.find(os.sep) > -1:
	path=path.split(' ')[0]
	path=path[:path.rfind(os.sep)+1]
else:
	path = ''

sys.path.append(path)
ScriptPath=path 

import ConfigUtils as cu

False=0
True=1


#########################################################################################################
#########################################################################################################
# Execution logic begins here 
#########################################################################################################
#########################################################################################################
if len(sys.argv) < 3:  #Ref0036
	print 'Syntax:'
	print '  python '+ sys.argv[0] + ' ReportFileName FileList1 FileList3 ...'
	print '    ReportFileName is the name of output report (fully qualified or relative)'
	print '    FileList parameters are lists of files generated by CollectFileData.sh' #Ref0036
#	print '    LibertyTarX is a tar file created by ConfigDumpLiberty.sh'
	sys.exit(0)

cu.printMsg('Begin run.',False)

fileIdx = 1
if sys.argv[0].find('.py') > 0:
	fileIdx = 2

ReportFileName = sys.argv[1]
cu.printMsg('Report file name: %s' % ReportFileName,False)

#Get information from input files
FileNames = sys.argv[fileIdx:]
for idx in range (0, len(FileNames)-1):
	FileNames[idx]=FileNames[idx].strip()
ServerDataList = cu.createServerFileDataList(FileNames) #Ref0030

#Run reports
cu.setReportOnlyMismatched("")
cu.reportInitialize('File System Report',ReportFileName)
cu.ReportFileSystem(ServerDataList)
cu.reportFinalize()

cu.printMsg('End run.',False)
